http:
  port: "8081"

sfdc:
  username: "eugene.bacolod@mulesoft.com"
  password: ""
  token: "JhHHM9MzEyICDQxy8tRILFIP"

file:
  caseDumpDir: "C:/Users/MILES/Downloads/RebexTinySftpServer-Binaries-Latest/data"
  
sftp:
  host: "localhost"
  port: "22"
  username: "MilesOng"
  password: "Zoidz123"
  
procCase:
  host: "proc-case.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
 
smtp:
  host: "sys-smtp.us-e2.cloudhub.io"
 
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
  
sysSalesforce:
  host: "salesforceapi-x5mpnz.5sc6y6-4.usa-e2.cloudhub.io"
cron: 
  scheduler: "0 0 * * * "